### ISSUE TITLE
Bugs in 1.4 alpha.

### ISSUE THREAD

**Issue by Atlantispy** [JMilamber/BrassArmory#12]
- [x] Crash when left clicking a boomerang stuck in a block due to it being an invalid entity.
- [x] Lazer arrow continues to move in a direction if the block it is stuck in is broken.
- [ ] Rope should have the #forge:rope tag for better mod compatibility.

**Comment by jodlodi** [comment]
Can't find an official forge rope tag? But fixed otherwise.
